//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        public string accno { get; set; }
        public string accfname { get; set; }
        public string acclname { get; set; }
        public string acccontact { get; set; }
        public Nullable<double> accamount { get; set; }
        public Nullable<int> accactive { get; set; }
    }
}
